### ISSUE TITLE
[API] Product should have category and sub category

### ISSUE THREAD

**Issue by TomashGombosh** [afj-solution/buy-it-api#24]
Add a Category object to the product as required field

**Given** User authorized
**And** User creates a product
**Then** Category field is required during the creation
**And** Sub category field is required during the creation

**Comment by KristianGombosh** [comment]
created product contains category and sub-category if this data provider in POST api/v1/products 
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/37942384/212104725-ff0cd6ad-c699-419d-afc3-abaeca84c906.png">

**Comment by TomashGombosh** [comment]
Was done in another user story. I close it
